# Generated by Django 3.1.1 on 2020-09-16 10:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('phoneNumber', models.CharField(default='#', max_length=18)),
                ('firstName', models.CharField(default='', max_length=16)),
                ('lastName', models.CharField(default='', max_length=16)),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(max_length=21)),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offerId', models.CharField(default='#1234567', max_length=8)),
                ('title', models.CharField(max_length=36)),
                ('description', models.TextField()),
                ('imageUrl', models.TextField()),
                ('callNumber', models.CharField(default='#', max_length=18)),
                ('avaibleQuantity', models.IntegerField(default=0)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('time', models.CharField(default='00:00Am', max_length=7)),
                ('active', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=12)),
                ('imageUrl', models.TextField()),
                ('dateText', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=36)),
                ('imageUrl', models.TextField()),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('time', models.CharField(default='00:00Am', max_length=7)),
                ('phoneNumber', models.CharField(max_length=18)),
                ('active', models.BooleanField(default=True)),
                ('budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('location', models.TextField(default='')),
                ('link', models.TextField(default='')),
                ('group', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mobile_api.group')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('imageUrl', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('assignedTo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_api.trip')),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends', models.ManyToManyField(related_name='friends_set', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
