# Generated by Django 3.1.1 on 2020-09-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imageUrl',
            field=models.TextField(default='https://image.flaticon.com/icons/png/512/10/10003.png'),
        ),
    ]
