# Generated by Django 3.1.1 on 2020-09-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=12)),
                ('imageUrl', models.TextField()),
                ('dateText', models.CharField(max_length=9)),
                ('phoneNumber', models.CharField(max_length=18)),
            ],
        ),
    ]
