# Generated by Django 3.1.1 on 2020-09-15 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0002_trips'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trips',
            new_name='Trip',
        ),
    ]
