# Generated by Django 3.1.1 on 2020-09-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0006_auto_20200915_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trip',
            name='title',
            field=models.CharField(max_length=36),
        ),
    ]
