# Generated by Django 3.1.1 on 2020-09-15 18:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0008_auto_20200915_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('GroupId', models.AutoField(default=10000000, primary_key=True, serialize=False)),
                ('GroupName', models.CharField(max_length=21)),
                ('Participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
