# Generated by Django 3.1.1 on 2020-09-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0009_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userId',
            field=models.AutoField(default=100000001, primary_key=True, serialize=False),
        ),
    ]
