# Generated by Django 3.1.1 on 2020-09-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0010_auto_20200915_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='handle',
        ),
        migrations.AddField(
            model_name='user',
            name='lastName',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstName',
            field=models.CharField(default='', max_length=16),
        ),
    ]
