# Generated by Django 3.1.1 on 2020-09-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0011_auto_20200915_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=models.CharField(default='#', max_length=18),
        ),
    ]
