# Generated by Django 3.1.1 on 2020-09-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0012_auto_20200915_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=36)),
                ('description', models.TextField()),
                ('imageUrl', models.TextField()),
                ('callNumber', models.CharField(default='#', max_length=18)),
                ('avaibleQuantity', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('time', models.CharField(default='00:00Am', max_length=7)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
