# Generated by Django 3.1.1 on 2020-09-15 18:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0013_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='dateText',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='limit',
        ),
        migrations.AddField(
            model_name='trip',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='trip',
            name='group',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='mobile_api.group'),
        ),
        migrations.AddField(
            model_name='trip',
            name='time',
            field=models.CharField(default='00:00Am', max_length=7),
        ),
        migrations.AlterField(
            model_name='offer',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
