# Generated by Django 3.1.1 on 2020-09-15 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0014_auto_20200915_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='group',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mobile_api.group'),
        ),
    ]
