# Generated by Django 3.1.1 on 2020-09-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0015_auto_20200915_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offerId',
            field=models.CharField(default='#1234567', max_length=8),
        ),
    ]
