# Generated by Django 3.1.1 on 2020-09-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0016_offer_offerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='Participants',
            field=models.ManyToManyField(to='mobile_api.User'),
        ),
    ]
