# Generated by Django 3.1.1 on 2020-09-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0017_auto_20200915_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
