# Generated by Django 3.1.1 on 2020-09-15 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0019_auto_20200915_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userId',
            field=models.AutoField(default=100000002, primary_key=True, serialize=False),
        ),
    ]
