# Generated by Django 3.1.1 on 2020-09-15 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0021_auto_20200915_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='assignedTo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mobile_api.user'),
        ),
    ]
